### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by MarcelCoding** [jellyfin/jellyfin-media-player#208]
**Describe the bug**
PC crashes randomly without a blue screen.

**To Reproduce**
While I am in a video stream my pc crashes randomly.

**Expected behavior**
Do not crash the whole pc.

**Desktop (please complete the following information):**
Windows 11: 
![image](https://user-images.githubusercontent.com/34819524/150648400-1e9c3b4f-94d8-4417-baa2-f9e03c106e2b.png)
Jellyfin Client: 1.6.1 (with installer)

**Additional context**
[JellyfinMediaPlayer.log](https://github.com/jellyfin/jellyfin-media-player/files/7918808/JellyfinMediaPlayer.log)
(please note the null bytes at the end of the file)

**Comment by sevenrats** [comment]
Hi, thanks for your report. It seems to me that this old issue is primarily related to SyncPlay hammering on the mpv api. It's not something that should be fixed in JMP even if it could be, which I'm not sure of.  Its simply the syncplay implemetentation in jellyfin-web. If you are still experience this issue on a supported version of JMP, please take a moment to determine whether or not it is limited to SyncPlay sessions. Please make your report is as specific and actionable as possible.
