### ISSUE TITLE
Q: Set default server at startup?

### ISSUE THREAD

**Issue by michael9dk** [jellyfin/jellyfin-media-player#213]
I've setup jellyfinmediaplayer (JMP) to launch in Openbox on top of LightDM, at startup (Debian Bullseye without a full DE - only Xorg, LightDM and Openbox). Like [this](https://unix.stackexchange.com/questions/30207/debian-based-system-only-one-gui-program-nothing-else/333559#333559).

Everything works well, but when JMP is launched from Openbox, it always asks me to 'Select Server', on startup. This doesn't happen when I start JMP within the same Openbox terminal. 

How can I set JMP to start with a default server?

**Comment by mijofa** [comment]
I've done very similar, and no there currently is no "official" way to do this. The way it would likely be done is to add support for Jellyfin's pre-existing "Automatic server discovery"
I discussed this at https://github.com/jellyfin/jellyfin-media-player/issues/168

I wrote my own workaround (as linked on that issue) by running a script before launching JMP. I attached a version of it there. I've since updated it to support a custom SRV record in my DNS config and to forcibly undo any "remember me" option that may have been applied by a user logging in. [/usr/local/bin/set/jellyfin/server.py](https://github.com/jellyfin/jellyfin-media-player/files/7968838/usr-local-bin-set-jellyfin-server.py.txt)
If you don't want to disable the "remember me" option, just comment out the last line

**Comment by michael9dk** [comment]
Thanks Mike.
That's a nice hack.

**Comment by mijofa** [comment]
I don't quite know how your system is setup, but it sounds like you don't have permanent home directory storage or it's being reset on logout/login, so upon reboot and auto-start of things there's a brand new config file, but once you're already logged in and manually starting it yourself it's still got that config file saved.
Nothing in that link you shared indicates to me that it's using a temporary or guest account, but I can't think of any other cause for this.

That's how I've *intentionally* configured mine to work as I usually use network booted systems with no local storage. (user's can't break things if they can't change things)

**Comment by michael9dk** [comment]
Hmmm, maybe something is running as root. Lightdm autologin as primary user, which also runs JMP + Openbox processes.

For the moment I settled for xdotool to press Return twice, after JMP is started.
So Openbox's autostart runs

```
# Disable screensaver
xset -dpms
xset s off

jellyfinmediaplayer &

sleep 4
xdotool search --desktop 0 --classname jellyfinmediaplayer windowactivate --sync key Return
sleep 1
xdotool search --desktop 0 --classname jellyfinmediaplayer windowactivate --sync key Return
```

**Comment by michael9dk** [comment]
Closing this, and refer to the feature request in #168
