### ISSUE TITLE
Add support for Intro Skipper and Jellyscrub plugins

### ISSUE THREAD

**Issue by tydog98** [jellyfin/jellyfin-media-player#300]
These plugins are gaining popularity and many other clients already support them out of the box. I would be nice if JMP did too.

**Comment by iwalton3** [comment]
I agree that it would be nice to properly support these extensions. I don’t recall that there has been a solution developed for conditionally serving extension components to the web client though, so that may take some work on the jellyfin-web side to do this right.

**Comment by Uncle-Tio** [comment]
(It's not a solution), but if this information is useful for anyone, there is a way to (manually) override the Media Player's web server (located at `C:\Program Files\Jellyfin\Jellyfin Media Player\web-client\desktop`), I used this to add Intro Skipper, but as I said, it is manually. I tried to recompile media player by myself but I'm very inexperienced, maybe someone more experienced can do it, it is only necessary to change which WEB server media player uses to compile 
And doesn't look like they use a different/modded Web server than the main one even though it is in a [separate fork](https://github.com/iwalton3/jellyfin-web-jmp), looks like the original but already compiled, it shouldn't be difficult for anyone (except me) to make this built-in mod.
(sorry if my English is bad)

**Comment by iwalton3** [comment]
> And doesn't look like they use a different/modded Web server than the main one

Correct. You can use any build of the Jellyfin web app. It used to require a special version, but all of the extensions needed for JMP to work were upstreamed a while back. The separate fork exists only because jellyfin-web does not publish prebuilt zip files of just the web client.

My hope is that eventually Jellyfin-Web will have a server-based extension loader for the web client, so that plugin developers don't have to hack the web client or replace it with an unofficial version to make this work.

**Comment by iwalton3** [comment]
This will be in the next release.
![image](https://user-images.githubusercontent.com/8078788/218343780-ac567d0c-d5c8-48a9-8bed-2e9fa7770eab.png)
