### ISSUE TITLE
DoVi  content direct plays even though it's not supported.

### ISSUE THREAD

**Issue by morkyy** [jellyfin/jellyfin-media-player#305]
Since 10.8 Jellyfin supports tonemapping for Dolby Vision content. I have set this up and it works correctly with every other client. However, with Jellyfin Media Player, DoVi content is not automatically transcoded and any such content just Direct Plays if the codecs are supported.

To reproduce, just play any dolby vision content that otherwise fulfills all the direct play criteria. The content will direct play instead of transcoding resulting in the green/magenta colours.

Expected behavior would be to test whether the content is DoVi and transcode if it is and the device does not support DoVi.

OS: Win11
Version: Latest version

**Comment by iwalton3** [comment]
This will be fixed in the next release, although I did have to implement a workaround to prevent it from remuxing for now.

There is also interest in allowing direct playing of DoVi content, but it requires either some fairly significant video rendering changes or for MPV to start supporting gpu-next in the libmpv video output. See: https://github.com/jellyfin/jellyfin-media-player/issues/362

If you want native playback of Dolby Vision, you can use MPV Shim with the `gpu-next` video output specified in the `mpv.conf`.
