### ISSUE TITLE
Shortcuts for playback speed

### ISSUE THREAD

**Issue by amau05** [jellyfin/jellyfin-media-player#323]
**Is your feature request related to a problem? Please describe.**
When there is a boring part in a video I like to change the playback speed and put it back to 1x after sometime quickly

**Describe the solution you'd like**
Keyboard shortcut to play the video faster or slower. 

**Describe alternatives you've considered**
Opening the cog in the player, go to playback speed, change speed, exit menu and do it again when needed... 

**Additional context**
It's slow and inconvenient to use that way we need to always have the mouse nearby. Before switching to Jellyfin I was using VLC and had remapped shortcuts to the numpad so when I wanted to speed up I pressed + to slow down -, to jump further in the video 6, to go back 4, to increase volume 8, decrease 2,... It's easier that way no need to "aim" in the menu. I find the current shortcuts less convenient but can live with them the only issue is there is none for playback speed...

**Comment by sevenrats** [comment]
Hi! Thank you for putting so much work into this! Unfortunately, per notes on the PR this needs to be implemented in jellyfin-web.
Please consider opening an equivalent PR.
Because this feature request relates to jellyfin-web and not JMP, the feature cannot be implemented here and should instead target jellyfin-web.
Thanks again!
