### ISSUE TITLE
AV1 hardware decoding

### ISSUE THREAD

**Issue by snakeeater4526** [jellyfin/jellyfin-media-player#326]
**Is your feature request related to a problem? Please describe.**
AV1 decoding use cpu but not gpu ( rtx 3080 here )

**Describe the solution you'd like**
use a video player that support hardware AV1 decoding ( mpv ?)

**Describe alternatives you've considered**
i mean it work with mpv locally and does not use cpu

**Additional context**
RTX 3080 here, RTX 3000 and now 4000 support AV1 decoding

**Comment by iwalton3** [comment]
Does the latest version of MPV correctly work with these files and GPU decoding? Currently JMP is stuck on a rather old MPV version since the libmpv2 API version is not compatible. I will likely need to do something terrible to support it any time soon, since not all platforms have the libmpv2 library available yet, but, if this fixes the hardware decoding issue, it may be worth implementing compatibility with both library versions.

One thing that may be worth trying is Jellyfin MPV Shim, since that works with the latest MPV versions. (The one bundled with it may still be too old, but you can upgrade it or use an arbitrary MPV binary you provide.)

**Comment by snakeeater4526** [comment]
i just retested the behavior.. and somehow.. i can't reproduce it anymore... 
it's strange because i was sure AV1 had problem before.. and now somehow it work well with gpu decoding... strange ( also i noticed the MPV dll i have is 2.0 and from 12/12/2021, normal? )

the only explanation i could find is either gpu driver update, or some dynamic dlls update .. idk.. very strange .

BUT there still some problem, for exemple 8k60fps AV1 video are a complete slideshow ( which doesn't happen on normal mpv or even firefox ). So there definitely some work to do

sorry if that issue was time consuming for no reason
