### ISSUE TITLE
Add option to disable the Windows media overlay

### ISSUE THREAD

**Issue by GermanCoding** [jellyfin/jellyfin-media-player#351]
**Is your feature request related to a problem? Please describe.**
Many people don't like Microsoft Windows media overlay, which always appears next to the volume bar. Many applications (Chrome, Firefox, Spotify, and many more) have options to disable this overlay. See for example this question: https://superuser.com/questions/1458379/disable-large-rectangle-from-windows-10-volume-overlay. Disabling this usually also disables the media keys, which is fine for me.

**Describe the solution you'd like**
An option in the media player settings that inhibits this overlay entirely (I believe this is internally done by not sending media information to Windows. All major browsers support this feature). This option may also control whether media keys are enabled or not.

**Describe alternatives you've considered**
The only alternative is running third-party software that continously runs in the background and hides the overlay. I would prefer not to add more third party software, which brings increased resource usage and security concerns, just for disabling an annoying Windows feature.

**Additional context**
N/A

**Comment by UnfinishedStuff** [comment]
I agree with this. I normally play media on my second monitor while I work on my main monitor, and for some reason these pop up on my main monitor where I'm working rather than in front of the Jellyfin client.  I know that's probably not a Jellyfin issue, but I'd be much happier if these could be disabled altogether, as I just don't find the popup useful, personally.

**Comment by iwalton3** [comment]
There will be a client setting in the next release called "enableWindowsMediaIntegration" to disable this.
