### ISSUE TITLE
External player?

### ISSUE THREAD

**Issue by gggirlgeek** [jellyfin/jellyfin-media-player#39]
Hello,

Is there a way to use an external player, like MPV-Easy Player or even VLC with Jellyfin Media Player? I know Jellyfin MPV Desktop can link to any other MPV player. Does JMP use MPV-type players and can it be set to use a different one?

The reason I ask is because my keyboard shortcut problems -- and many other customization tweaks -- would be solved using my own player. I use JMP because it is faster and it stays connected to the server better than Jellyfin MPV Desktop (which I have to restart constantly.) I really love this desktop client. Thank you!

Win10pro v2004
JMP v1.2.1 Desktop/Auto mode
Jellyfin Server v10.6.x on Ubuntu 18.6 managed seedbox

**Comment by iwalton3** [comment]
Unfortunately Jellyfin Media Player only supports the embedded libmpv1 library and is not written to respond to changes performed to MPV outside of actions performed in the web player.

Support for external players is not planned. This software is completely different from Jellyfin Desktop which is written to support external MPV players and respond appropriately to the respective events, instead of operating in a fashion entirely controlled by jellyfin-web as this one is.

You will likely be served better by using Jellyfin Desktop for this purpose. If you would like to troubleshoot the frequent disconnect issue please open an issue on Jellyfin Desktop and send the applicable logs.
