### ISSUE TITLE
Regression from 1.8.1 to 1.9.0 No longer plays AV1 directly

### ISSUE THREAD

**Issue by Pingger** [jellyfin/jellyfin-media-player#400]
**Describe the bug**
After updating from 1.8.1 to 1.9.0 I can no longer play AV1 encoded video directly. It now forces a reencode on the server. 
**Additionally:** The client completely disregards which movie-"version", audio and subtitle is selected and just reverts to the defaults upon clicking play
**Additionally 2:** I can't uninstall 1.9.0 "because a reboot is required", even after several reboots

**To Reproduce**
1. Open movie-details page of a movie with multiple video versions (e.g. a 4K and a 1080p encoded AV1 version)
2. Select a anything not default
3. Hit play on the top right bar, or click the Movie Cover on the left
4. Notice, that even before the player fully loads, the selection reverts
5. In the player notice, that the visual changes after hitting play persist into the player.
6. And additionally notice, by opening the "playback info", that the video is being transcoded to much more Mbps, that actual source file. (in this case from 3.7Mbit/s up to 6Mbit/s)

The stated Reason: "The video's bitrate exceeds the limit" (Yes transcoding from 3.7MBit/s to 6MBit/s totally makes sense, when the bitrate was "too high")
Stated Limit is 10Mbit/s clientside, unlimited serverside

**Expected behavior**
to just play the source file like in 1.8.1

**Screenshots**
![image](https://user-images.githubusercontent.com/4761298/225139370-648ea53c-6e69-49f3-8515-c1940c8433a8.png)
![image](https://user-images.githubusercontent.com/4761298/225139410-0a469273-0e89-41bf-a44f-f8ac419653d8.png)
![image](https://user-images.githubusercontent.com/4761298/225139448-353be698-9480-4cd3-9036-c4bc397750d0.png)
![image](https://user-images.githubusercontent.com/4761298/225144364-a4308685-ad73-44dc-a09a-1558d1de17e6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10.0.19045.2251
 - Installation Method: Windows 64bits installer

**Additional context**

[.log](https://github.com/jellyfin/jellyfin-media-player/files/10973906/trash.log)

**Comment by Pingger** [comment]
After having been forced to use a tool to help uninstalling 1.9.0, I can now no longer successfully install ANY version.
Seriously something very broken with 1.9.0
Since the Tool has now lost its entire usefulness for me (which is playing AV1 directly) and I can't even install it anymore, it seems this is a goodbye from the Jellyfin media player. back to web ui

[Jellyfin_Media_Player_20230314225431.log](https://github.com/jellyfin/jellyfin-media-player/files/10974071/Jellyfin_Media_Player_20230314225431.log)
[Jellyfin_Media_Player_20230314225845.log](https://github.com/jellyfin/jellyfin-media-player/files/10974075/Jellyfin_Media_Player_20230314225845.log)

**Comment by iwalton3** [comment]
Looks like HDR AV1 playback is working fine on Windows and Linux.
![image](https://user-images.githubusercontent.com/8078788/225156739-2208c4c7-5e79-4d5b-9fe2-1c955754b4d0.png)
![image](https://user-images.githubusercontent.com/8078788/225156653-0261f204-405a-4dc8-8053-5c32fe4d9676.png)

I suspect what is happening is a bandwidth limit is getting set. I see `MaxStreamingBitrate=10000000` in the log as a playback parameter. This would be 10 mbps which is not the default.

Please make sure that the video settings are set to Auto:
![image](https://user-images.githubusercontent.com/8078788/225157150-54669471-66dd-427a-82e3-12300affbf64.png)
Additionally try setting Video Quality to 120 Mbps under Playback:
![image](https://user-images.githubusercontent.com/8078788/225157666-3533ba07-2bc6-48d4-94fb-cd2b8b7025e6.png)

> Installer issues...

I am growing frustrated with the installer too as a maintainer. It has caused a number of issues and I am getting increasingly close to replacing it with something else. It was inherited from Plex Media Player and has been a pain to work with.

What we can try doing is wiping all traces of it out of the registry. If you navigate to one of the listed registry keys and it does not exist, continue to the next one.

Try deleting each of these registry keys:
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{DE7FA262-4963-487E-A495-CE60B29BBDD8}
Computer\HKEY_CLASSES_ROOT\Installer\Dependencies\{DE7FA262-4963-487E-A495-CE60B29BBDD8}
Computer\HKEY_CLASSES_ROOT\Installer\Products\262AF7ED3694E7844A59EC062BB9DB8D
Computer\HKEY_CLASSES_ROOT\Installer\Dependencies\{60474fed-3187-42ff-946e-45be45312ddc}
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{60474fed-3187-42ff-946e-45be45312ddc}
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{60474fed-3187-42ff-946e-45be45312ddc}
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Installer\Dependencies\{DE7FA262-4963-487E-A495-CE60B29BBDD8}
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MATS\WindowsInstaller\{60474fed-3187-42ff-946e-45be45312ddc}
```

1. Open `regedit`.
2. Use the menu option File > Export.
3. Select "All" under "Export Range".
4. Give it a name and click save.
5. For each of the above registry keys, use the textbox below the menu bar to navigate to it. (Press CTRL+A to select all, backspace, paste the key in, and press enter.)
6. Use the menu option Edit > Delete.
7. Go to `C:\Program Files\Jellyfin` in a file browser.
8. Delete `Jellyfin Media Player`.
9. Run the FixIt Troubleshooter here: https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed
10. Select that you have difficulty uninstalling programs.
11. Select "Not Listed".
12. Enter the program ID `{DE7FA262-4963-487E-A495-CE60B29BBDD8}`.
13. Select "Yes, try uninstall."

I intentionally corrupted my install and the above steps cleared it up so that it runs again.

> Since the Tool has now lost its entire usefulness for me (which is playing AV1 directly) and I can't even install it anymore, it seems this is a goodbye from the Jellyfin media player. back to web ui and pasting links into vlc

Please remember that I do this for free in my spare time. Lots of open source maintainers quit or burn out from hostility.

**Comment by Pingger** [comment]
> Please remember that I do this for free in my spare time. Lots of open source maintainers quit or burn out from hostility.

Yes I'm aware ... sorry. I have been at the receiving end at times of such hostility. I was a contributors to the nextcloud project, until I was so fed up with some users and other contributors, that I asked to be completely removed from the project.

# Installer
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{DE7FA262-4963-487E-A495-CE60B29BBDD8}` was the only one that I could find.
The described steps **resolved** the installation troubles.

# AV1 issue
The described setting in the Playback-Section is somehow missing in the 1.9.0
![image](https://user-images.githubusercontent.com/4761298/225396900-17d60d2c-ac5a-47c7-8080-1dc7981d265e.png)
![image](https://user-images.githubusercontent.com/4761298/225396915-e51876ed-e393-4891-99b8-f70116406441.png)

I have partially resolved the issue, by disabling the user setting for video transcodes:
![image](https://user-images.githubusercontent.com/4761298/225397629-bc9c06fb-9814-470c-9a6f-10400226c1f7.png)
which seems to force a direct playback unfortunately it still uses the 4K version despite selecting the 1080p version...
![image](https://user-images.githubusercontent.com/4761298/225397843-0ea5d70c-18fd-44ec-b416-3649c532f855.png)

**Comment by Pingger** [comment]
Ok,
the playback settings missing for video playback was caused by disabling transcoding for the user serverside.
Changing to "Auto" during playback makes jmp use direct playback. The main issue seems to be the wrong Bitrate detection. As I only have 10Mbps throughput to my jellyfin, that is what I set in the settings. The detected wrong bitrate then prompting the reencode.
And then after fiddeling around and verifying the Playback Settings noticing, that they are only saved when clicking the "save"-Button at the bottom, that is hidden until you scroll down -.-

I'm unsure whether to close the issue as resolved or not. 

The cause of the issue I found to be the wrong bitrate detection. Not sure if that is server-side or client-side.

**Comment by iwalton3** [comment]
It might be based off of peak bitrate for the file instead of average bitrate. If you set it to 10 Mbps though then it would be a server issue. This issue can be closed regardless, since if it was detected automatically that is a jellyfin-web feature.

**Comment by Pingger** [comment]
The Peak bitrate is 8MBit/s ... at least if ffmpeg respects the `-maxrate:v` flag ... But I see, that it isn't a JMP issue ...
