### ISSUE TITLE
Remember Playback speed

### ISSUE THREAD

**Issue by zocke1r** [jellyfin/jellyfin-media-player#414]
**Is your feature request related to a problem? Please describe.**
When going to the next video the playback speed gets reset back to 1x

**Describe the solution you'd like**
The last used playback speed is remembered and used when watching the next video.

**Describe alternatives you've considered**
Setting the playback speed each time manually, but this feels unnecessarily tedious.

**Comment by JackMaiden** [comment]
Due to line 158 in mpvVideoPlayer.js, I've resorted to hard coding it each release until I get time to find a way round it. It appears without setting each time the UI gets a little confused. 

https://github.com/jellyfin/jellyfin-media-player/blob/69d1b871fc013c5299de565748cd79fe938bf978/native/mpvVideoPlayer.js#L158

on install for windows can be found in "C:\Program Files\Jellyfin\Jellyfin Media Player\web-client\extension\mpvVideoPlayer.js"
