### ISSUE TITLE
Default values and setting mpv.conf

### ISSUE THREAD

**Issue by Ashyni** [jellyfin/jellyfin-media-player#44]
Hello,

I want to talk about some default values of libmpv, like `audio > channels > stereo` that trigger audio transcoding with any non-stereo input, this should be back to `auto-safe`([default](https://mpv.io/manual/stable/#options-audio-channels)) to allow direct play in any situation by default.

Another value is `hardwareDecoding > decode.enabled`, this can lead to more trouble than actual benefit,
> In general, it's very strongly advised to avoid hardware decoding unless absolutely necessary, i.e. if your CPU is insufficient to decode the file in questions. If you run into any weird decoding issues, frame glitches or discoloration, and you have --hwdec turned on, the first thing you should try is disabling it. ([source](https://mpv.io/manual/stable/#options-hwdec))

It also prevents video filters to be used, which required `hwdec=no` or any `*-copy`.

Other topic, would it be possible to directly edit mpv.conf inside the Media Player, it would be easier to maintained and allow a full customization, or did you plan to map more setting in the current client page ?

Thanks for all the work already done.

**Comment by iwalton3** [comment]
You can create an `mpv.conf` in the configuration folder at `%localappdata%/JellyfinMediaPlayer/mpv.conf` or `.local/share/jellyfinmediaplayer/mpv.conf` depending on your platform. Note that some settings managed by the player may be overriden.

> audio > channels > stereo

This is great until you end up with someone on a strange audio system and they don't hear the center channel at all for instance. People have complained about this in the past, so stereo is a safer default. Anyone who wants surround sound should probably configure it as then they can also enable passthrough if applicable.

> hardwareDecoding > decode.enabled

I enabled hardware decoding by default because it can greatly reduce power usage and stuttering of the video. For instance I tested a video and it reduced CPU usage by 80 percent. But I understand that the default could render the client inoperable on more configurations. If this becomes a recurring issue I will ship another update that disables it by default again.

**Comment by ahmed2m** [comment]
Can I also have input.conf in the `.local/share/jellyfinmediaplayer`? I wanted to have some extra shortcuts like change subtitle position and subtitle size configured (I know gui have an option for size but shows might have already embedded styled captions won't be within the same scale of 'normal'), can custom libmpv shortcuts be achieved?

**Comment by iwalton3** [comment]
> can custom libmpv shortcuts be achieved?

No. MPV does not capture input directly. It is sent to the Jellyfin web client and then is forwarded back to MPV in a limited capacity. You may consider using MPV Shim if you want a client that offers input.conf for now, as it allows more customization and can deal with more unexpected things happening in MPV.

MPV config and scripts are supported though.

**Comment by iwalton3** [comment]
I put out a survey and it looks like `enabled` is causing color issues (HDR maybe or just strangeness with brightness?), so it will tentatively be defaulted to/migrated to `copy` in the next release.

**Comment by iwalton3** [comment]
Closing as stale.
