### ISSUE TITLE
macOS Mojave (10.14) support ?

### ISSUE THREAD

**Issue by Ribero** [jellyfin/jellyfin-media-player#46]
Any chance to make this nice application to work on Mojave or is it mandatory bound to Catalina ?

**Comment by iwalton3** [comment]
This depends entirely on if outside contributors are able to get it working. Note that the build system uses Catalina, so this may pose issues to shipping for older versions.

**Comment by yxwangcs** [comment]
If we want support of Mojave or earlier, we need to set the macOS deployment target to be lower. It not only needs to be set for jellyfin media player itself but also all its dependencies (mpv / FFmpeg and their dependencies as well).

However, [homebrew is configured to target the macOS version it is built on](https://github.com/Homebrew/legacy-homebrew/issues/48437#issuecomment-174522431) and GitHub Actions doesn't provide older macOS. This means we need to build everything from source and set the deployment target to be 10.14. So with the help of [mpv-nightly-build](https://github.com/jnozsc/mpv-nightly-build) I hacked the homebrew formulae and build a version that targets 10.13, and runs well in a vm. But [it takes ~2.5hrs to finish](https://github.com/yxwangcs/jellyfin-media-player/actions/runs/780940163). We could possibly strip out some unnecessary dependencies (maybe some encoders for ffmpeg), but the total time would still be substantially longer than before. Caching may help but I read somewhere that GitHub Actions only keep cache for a week or so.

@iwalton3 not sure what you think, maybe we could have two build configs where mpv is only built on release branch and on test branch we just simply run `brew install mpv`.

Just a side note if we want to support Mojave: for macOS 10.14.3 and earlier, we need to bundle swift libraries otherwise the user has to install [swift runtime](https://support.apple.com/kb/DL1998?locale=en_US).

**Comment by iwalton3** [comment]
I'd say if someone in the community wants to do this that's fine, but the 2.5 hour build process thing is kind of a deal-breaker. I am of course willing to change my mind on this if a ton of people request it though.

**Comment by ripley1901** [comment]
Jellyfin has clients for all kinds of tv os, but still no easy-to-use clients for mac except for kodi plugin and it's performance is not ideal on mac.
I believe there's lots of Mac users like me who still stuck in older mac os, either for old hardware or lack of attracting new feature on newer os worth the upgrade.

**Comment by iwalton3** [comment]
Yeah it's just unfortunate that all the build infrastructure and packaging has moved on. So you have to do things like multi-hour CI builds.

**Comment by iwalton3** [comment]
If someone can make a GitHub Actions job that builds in under 40 minutes I'd gladly use it.

**Comment by jameskimmel** [comment]
> Jellyfin has clients for all kinds of tv os, but still no easy-to-use clients for mac except for kodi plugin and its performance is not ideal on mac.
I use Chrome for my old Mac and it works pretty good. Maybe give that a try?

**Comment by Ribero** [comment]
Probably not worth the effort of having a pre Catalina version of the client in regards to the number of potential users. And I support the fact that ressources should concentrate on new features. 
That makes sens.

**Comment by findyy99** [comment]
So, may I ask that is there any release for 10.14 now?

**Comment by MrAlucardDante** [comment]
1.8 is no longer compatible with Catalina and requires at least Big Sur. We can still downgrade to 1.7, but that’s really unfortunate

**Comment by sevenrats** [comment]
Mojave has been EoL for two years. You will have to follow the instructions to build yourself on unsupported operating systems.
Stop by the chat spaces and I will help you build it.
