### ISSUE TITLE
subtitles position

### ISSUE THREAD

**Issue by Knetsu** [jellyfin/jellyfin-media-player#474]
Is there an option to move the position subtitles? It would be of great help for people who want to move the subtitles position. Should there be an option on the keyboard, or how can I modify the jellyfinmediaplayer.conf that I should add?

**Comment by florentc** [comment]
This is not true. Subtitle position cannot be modified in mpv.conf on version 1.9.1.

The `sub-pos` option in `mpv.conf` is ignored and overridden by the `subtitles.placement` option in `jellyfinmediaplayer.conf`.
Same issue with `sub-color`.
However, `sub-bold` is taken into account for example.

I think this issue should be reopen @sevenrats.

**Comment by sevenrats** [comment]
can you help the reader understand why the current options are insufficient?

**Comment by florentc** [comment]
Thank you for reopening the issue. The current options are insufficient because the right subtitle position can be a matter of a few dozens of pixels on the screen.

The current options for vertical position are basically top and bottom on the edge of the screen.

Some people struggle to read subtitles that are too far from the center of their vision because of vision impairment. Some users are just used to centered subtitles (see #289). Some users view content that already includes text on the edge of the screen (or other important information) which, if not taken into account by the subtitles, may be hidden by the subtitles and require a slight offset to the top or bottom for comfort. That offset would conveniently put the subtitles in an intermediate vertical position that is neither top edge, middle, or bottom edge. Every user might have their sweet spot for subtitles in an intermediate position for various reasons.

There are many use cases for fine-tuned vertical position. I think it would be nice if the `sub-pos` options in `mpv.conf` was taken into account when present. Or if the `subtitle.placement` option in `jellyfinmediaplayer.conf` allowed for values between 0 and 100 for horizontal and vertical position. Or at least adding a `center` option for vertical position, and maybe `slightlyTop`, `slightlyBottom`.

**Comment by sevenrats** [comment]
@florentc after reviewing a broader set of the reported issues, its clear that this is a widespread and complex issue. I am unifying all of these under a new dicussion threadm because its not immediately clear what the best way to satisfy everybody's needs is.  This thread will be linked there, and if you have anything to add, I think here or there is perfectly appropriate.
#543
