### ISSUE TITLE
Crop Video to:

### ISSUE THREAD

**Issue by DerP4si** [jellyfin/jellyfin-media-player#517]
**Is your feature request related to a problem? Please describe.**
If a Video is rendered in 16:9 but the content is originaly 20:9 and you're watching on a 21:9 monitor, it has big black bars under and over it, that don't need to be there...

**Describe the solution you'd like**
Add a button like: Crop video to (f.e. vlc:
![image](https://github.com/jellyfin/jellyfin-media-player/assets/28807283/d148e6ec-563b-4c30-ae66-6c123a1aa209)
)

Another Solution (web only) is the extension: Zoom to Fill
![image](https://github.com/jellyfin/jellyfin-media-player/assets/28807283/d5bd2c87-ff3e-4043-a379-17c66937ec43)

**Additional context**
Uncroped:
![image](https://github.com/jellyfin/jellyfin-media-player/assets/28807283/d98e890a-2370-47dc-b941-697053dd5a35)

Croped:
![image](https://github.com/jellyfin/jellyfin-media-player/assets/28807283/315a5322-a91b-4ed0-ab75-c32fc243ed91)

**Comment by iwalton3** [comment]
There should be an aspect ratio option in the player options when you actually go to play a video.

**Comment by DerP4si** [comment]
Yeah, but every Movie/TV-Show is different... So you could end up cutting non-black areas of the video...

**Comment by DerP4si** [comment]
i missread... The aspect ratio option is stretching the video but not croping it:
![image](https://github.com/jellyfin/jellyfin-media-player/assets/28807283/e887b933-e7f5-4171-b449-16c7840780c2)

**Comment by iwalton3** [comment]
While not a real solution to this problem, if you use SVP with Jellyfin Media Player it will remove the black borders burned into videos. I can't easily add that feature without extending MPV.

It does look like people have made MPV scripts that can do it:
 - https://github.com/Ashyni/mpv-scripts#dynamic-croplua
 - https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autocrop.lua

**Comment by DerP4si** [comment]
Sry... SVP? MVP? 😅 I get that it is a mediaplayer... Is jellyfin desktop based on it? I cant find %AppData%\mpv\scripts\ or did i misunderstand sth?

**Comment by iwalton3** [comment]
Jellyfin Media Player uses MPV as the playback backend

**Comment by DerP4si** [comment]
Ok and where to add the scripts?

**Comment by DerP4si** [comment]
Found it... Sry I just had to read the documentation 😅 The first script you provided works already (except the SHIFT + C shortcut)! As a workaround - as long as you can't edit the MPV repo - you could provide that script as default, so it is installed by default and can be deactivated via an additional button f.e. 😃

**Comment by adamzimnyy** [comment]
There is an option for this, but it's buried deep in the settings. 

It's under hamburger menu > Settings > Client settings > Aspect: Zoom (all the way at the bottom) 

![image](https://github.com/jellyfin/jellyfin-media-player/assets/14812161/b99dfaea-95d6-49e2-9a0a-1e6e43e35a8e)


It should be made available right on the video during playback, otherwise it's a pain in the ass to change it. And if you have a mix of movies, some with black bars are some without, or 16:9 tv shows, you need to change it every time. 


I tried the script which should do it automatically before and it works, but it causes issues with playback (stuttering), so it's not really a solution.

**Comment by DerP4si** [comment]
Yeah, i found that to but as you just said it's not really the solution I'm looking for.The stuttering on the other hand is something that I don't experience.

**Comment by Uncle-Tio** [comment]
Dynamic-crop works perfectly for me:

I put the [dynamic-crop.lua](https://github.com/Ashyni/mpv-scripts#dynamic-croplua) in `C:\Users\USERNAME\AppData\Local\JellyfinMediaPlayer\scripts`, and make sure that line 59 (`mode = X, -- [0-4] more details above`) has "mode = 4".

In the Jellyfin Media Player, I go to the client options and enable the use of OpenGL (otherwise, stuttering happens). All content auto-crops when needed and does nothing when not needed.

**Comment by DerP4si** [comment]
I also discovered that if the intro is in 16:9, it doesn't crop afterwards. I think a crop menu, like VLC, would be the best solution, or at least an additional option to the auto-crop feature.

**Comment by sevenrats** [comment]
any objection to closing this resolved issue?

**Comment by adamzimnyy** [comment]
I still this this menu 

![image](https://github.com/jellyfin/jellyfin-media-player/assets/14812161/824999a8-0c52-425e-9a82-b36548e7e85b)
 
being available directly on the video player would be a better solution than a third party script

**Comment by DerP4si** [comment]
True, i forgot that this is a 3rd party solution... I think it would be better if the client comes with this script pre-installed so other people with the same problem don't have to google anything...
Or am i wrong?

**Comment by sevenrats** [comment]
@adamzimnyy this is blocked for the forseeable future because the web ui inside JMP already has these elements in it. JMP does not modify the web elements at all. this means that for JMP the app, outside of the web ui to affect the setting, it needs to be outside the OSC of the web ui.  the qt6 branch will eventually need a custom osc built for it, so this behavior will naturally change when that happens.

**Comment by sevenrats** [comment]
@DerP4si you highlight a second problem with this particular issue 517 is that its no referring to two separate feature requests.  the "solution" i refer to above is the fact that JMP already exposes these settings.  A feature request to integrate the script is appropriate if you want it. a feature request to move the existing setting to the video player is not necessary, because it will all ready happen in the long term at a pace more or less outside of our control.
