### ISSUE TITLE
Feature Request: to be able to select multiple item at a time

### ISSUE THREAD

**Issue by opi3636** [jellyfin/jellyfin-media-player#524]
**Is your feature request related to a problem? Please describe.**
for episodes of a tv shows i like to use a generic image, and without the option to select more then one item at a time its really annoying and time consuming to remove all the images manually   

**Describe the solution you'd like**
to have the option to select multiple episodes of a tv show and edit images/subs and add the a playlist/collection

**Comment by sevenrats** [comment]
Hi, thanks for this report! Because you are actually asking for a feature to be implemented in github.com/jellyfin/jellyfin-web (which is a ui component inside of JMP) you should move this feature request to features.jellyfin.org
as it is, there is no chance of it being implemented here.

p.s. Have you tried the metadata editor? It's available to admin users in the dashboard.
