### ISSUE TITLE
Connection Failure to server which hosted under subpath

### ISSUE THREAD

**Issue by dragoangel** [jellyfin/jellyfin-media-player#559]
**Describe the bug**
When server served from under subpath Jellyfin meia player throws error about failed connection. From web and Android clients everything works good at same time. 

**To Reproduce**
1. Install jellyfin-media-player
2. Add new server as URL: https://example.com/jellyfin/ (non-default base URL)

**Expected behavior**
I expect that server will be added properly

**Desktop (please complete the following information):**
 - OS: **Windows 11**
 - Version **1.9.1**
 - Installation Method **windows installer**

**Comment by sevenrats** [comment]
remove the trailing slash.

**Comment by dragoangel** [comment]
The issue that no trailing slash is different URL

**Comment by sevenrats** [comment]
If you want support with your reverse proxy, stop by the chat spaces on Matrix or Discord.  There *is* a known idiosyncracy with JMP that requires you to configure your reverse proxy correctly, while other clients are more tolerant of small malconfigs like trailing slashes.  The real reason this issue was closed is because it is a duplicate report for that issue:
https://github.com/jellyfin/jellyfin-media-player/issues/280
