### ISSUE TITLE
Media does not play. Command loadfile: argument index has incompatible type.

### ISSUE THREAD

**Issue by MenchenFive** [jellyfin/jellyfin-media-player#579]
**Describe the bug**
App launches fine and allows for navigation between all the different menus and libraries. However, whenever the play button is pressed in order to reproduce video or audio files.

When attempting to play audio bottom bar shows, but player appears always paused. Timeline shows --:--. App is still responsive, but audio never starts. (Screenshot 1)
With video, spinner loader shows for a second, then app becomes unresponsive, no elements react to mouse click. It is possible to right-click anywhere in screen and reload, which unfreezes the app. (Screenshot 2)

I have observed a critical error in the attached log file:` [critical] PlayerComponent::handleMpvEvent @ 597 - main: Command loadfile: argument index has incompatible type.
`
Which happens immediately after clicking play, preceded by some other log lines.

**To Reproduce**
1. Attempt to play media
2. Fail :(

**Expected behavior**
Either mpv or in-app player launching and playing the file.

**Screenshots**
![Screenshot_20240313_181656](https://github.com/jellyfin/jellyfin-media-player/assets/36774104/faa6bc17-6fe6-4d6c-b632-6101348c1081)
![Screenshot_20240313_181951](https://github.com/jellyfin/jellyfin-media-player/assets/36774104/e66018f6-7154-4ebf-9543-6e53142cb3ff)

**Desktop (please complete the following information):**
 - OS: ArchLinux (updated as of March 13th 2024)
 - DE: KDE Plasma 6, X11
 - Installation Method: AUR package jellyfin-media-player 1.9.1-2

**Additional context**
[jellyfinmediaplayer.log](https://github.com/jellyfin/jellyfin-media-player/files/14591455/jellyfinmediaplayer.log)

**Comment by sevenrats** [comment]
please try this:
https://github.com/jellyflix-app/jellyflix/issues/46#issuecomment-2002101672

**Comment by svarqq** [comment]
Same issue, my logs look pretty much the same as those uploaded by MenchenFive. I tried softlinking to the mpv2 library in `/usr/lib/local/x86_64-linux-gnu` and `/usr/lib/x86_64-linux-gnu` as suggested by @sevenrats  and it didn't help. More specifically, I softlinked `libmpv.so`, `libmpv.so.1` and `libmpv.so.2` in the directories mentioned before
- first to non-symlinked, built-from-source `libmpv.so.2.0.3`, and after continued failure
- to non-symlinked `libmpv.so.2.0.2` provided by a package from my distribution

Desktop:

    OS: OpenSUSE Tumbleweed
    DE: KDE Plasma 6, X11
    Installation Method: Built from source, from tag `v1.9.1`

**Comment by svarqq** [comment]
Solved. Using `ldd` I figured out that the `jellyfin` binary was looking for libmpv at `/usr/local/lib64/libmpv.so.2`. It works when symlinked against `libmpv.so.2.2.0`, but not `libmpv.so.2.3.0`. Not sure if that's a result of not correctly building `libmpv.so.2.3.0`, or if its interface has changed since `2.2.0`, but regardless it works.

**Comment by arf20** [comment]
Hello I just upgraded to Debian trixie. Official packaged jellyfinmediaplayer looks for `/lib/x86_64-linux-gnu/libmpv.so.2` which exists and its a link to `libmpv.so.2.5.0`.

I'm getting 

```
[critical] unknown @ 0 - main: Command loadfile: argument index has incompatible type.
```
In the log.

**Comment by zoot101** [comment]
I ran into this issue, and given this issue was one of the 1st I found via internet search I figured I would add to it.

I too did an upgrade from Debian Bookworm to Trixie, and I got this error each time I was trying to play a video file after the upgrade. The player would just freeze and do nothing, but the message:
```
[critical] unknown @ 0 - main: Command loadfile: argument index has incompatible type.
```

...would appear in the logs for the Jellyfin media player client. Nothing would show up in the Server logs.

What fixed the issue for me was to install the package built for Debian Trixie as during the upgrade from Bookworm to Trixie the Jellyfin Media Player package of course was not upgraded since I installed it by the package provided on the Github releases page. After I did that the client worked just fine as before.

Debian Trixie and Bookworm have different underlying implementations of the dependencies, hence the need for different packages on the release pages. I'd have thought the upgrade would break the dependencies for the Bookworm package, but apparently not.

Anyway, hopefully this is of use to someone else who stumbles upon this issue here.
