### ISSUE TITLE
1.10.0 doesn't work on windows 11

### ISSUE THREAD

**Issue by bear0328** [jellyfin/jellyfin-media-player#624]
I updated to v1.10.0,I can't see any media library. but in the dashboard,I can find the library

**Comment by carfanatic93** [comment]
Same Problem here.

**Comment by DawidB** [comment]
Same problem on my side. Favorites are visible and usable though.

**Comment by ThorpeJosh** [comment]
same on windows 10 and arch linux

**Comment by jsayol** [comment]
I just updated the media player to 1.10.0 and it works ok for me on Windows 11 Pro 23H2 (22631.3527) using Jellyfin Server 10.9.1

**Comment by heunghingwan** [comment]
Fixed after updating server to 10.9.1, seems to be incompatible with older servers

**Comment by DawidB** [comment]
Confirmed, server update fixed the issue on my end as well.

**Comment by M450NC** [comment]
Same issue here.

**Comment by 31bado** [comment]
Media Player is not installing on Win10 with last version server.

**Comment by WXpiero** [comment]
Same Problem here with Server Version 10.8.13. all my windows10 and windows11 computers are cannot see movies now

**Comment by iwalton3** [comment]
JMP v1.10.0 requires a Jellyfin server version of v10.9.1 or later to work. Older server versions will result in an empty home screen.

**Comment by WXpiero** [comment]
well, thanks for your reply,but after I upgrade my jellyfin server to 10.9.1, it becomes crash all the time after I started it. it was setup on a windowsX64 virtual enviroment, nothing special.


国产cpu/ka
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jellyfin/jellyfin-media-player"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月16日(星期四) 中午1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jellyfin/jellyfin-media-player] 1.10.0 doesn't work on windows 11 (Issue #624)





 
JMP v1.10.0 requires a Jellyfin server version of v10.9.1 or later to work. Older server versions will result in an empty home screen.

**Comment by Darkhost1999** [comment]
Alright, thank you for pinning this bug report even after it was closed.
![Screenshot_20240521_175343_Jellyfin](https://github.com/jellyfin/jellyfin-media-player/assets/60384196/34b7b458-9830-4419-8ea6-00d8f6526c61)
I can access Jellyfin from my phone, and my android TV;
But as you will see in screenshots I can't access from the Web UI or the updated Media Player application (previous versions work fine).
Here is my detailed report.
I saw Jellyfin 10.9 released and I immediately updated by right clicking my tray icon clicking stop, and then Exit.
I went to GitHub -> notifications and saw there were no compiled builds in the release tab.
I went to the Jellyfin website. Downloaded the 10.9.0 AMD64 (current at time of events).
I installed it and then went to open the web-ui. Saw this issue.
I ignored it and saw my phone and Android TV still worked.
I waited for 2 more updates. Skipped installing 10.9.1 and installed 10.9.2 which I am currently running.
How I installed was simply to stop Jellyfin and exit from my tray icon. Next next next. Finish. I could see that Jellyfin was able to identify my install existed then upgraded it.
In Troubleshooting I have tried deleting my ProgramFiles/Jellyfin/Server folder and reinstalling. Upon no success I restored the folder from my recycling bin and ignored it.

Here is that screenshot showing I had only tested the web ui so far.
![Screenshot 2024-05-21 174221](https://github.com/jellyfin/jellyfin-media-player/assets/60384196/fae83b29-1b78-408a-92c6-9ae03231ded3)

Today I was testing the media player to see if it didn't have the web-ui's problem since this issue was reported as closed and fixed and so I figured I will just use the media player until the webui is back online and working. But here are the results.

![Screenshot 2024-05-21 174232](https://github.com/jellyfin/jellyfin-media-player/assets/60384196/6d3c3422-8b60-471d-b1d7-5501162b757a)

![image](https://github.com/jellyfin/jellyfin-media-player/assets/60384196/627770e7-3475-4e2e-a28c-f2fbb8111ae5)

Before updating the media player at all I saw all my movies and shows available to watch and to view all my accounts worked and I had only had the notification that an update was available. So I will be reverting back the media player in the event that my other troubleshooting step of installing the 10.9.1 server version then updating from that version doesn't work.
I figured since I had skipped installing 10.9.1 I might as well give it a try now by rolling back to that version then see if it works. If it does. Upgrade from that version and see if continued working.
Ultimately the solution is to just downgrade the media player instead of the server if nothing else works.

**Comment by MattMckenzy** [comment]
I had the same problem, but I could fix it simply by deleting JMP's local storage. I had three jellyfin folders in "~/.local/share/" and once I deleted them all, I could re-add my server and use the app again.

Hopefully that helps someone!

**Comment by kin0be** [comment]
> I had the same problem, but I could fix it simply by deleting JMP's local storage. I had three jellyfin folders in "~/.local/share/" and once I deleted them all, I could re-add my server and use the app again.
> 
> Hopefully that helps someone!

Just wanted to say thanks, this worked. On Windows, you can find the folder to delete at C:\Users\{yourWindowsUser}\AppData\Local. Delete the folder with spaces, i.e. "Jellyfin Media Player". Of course, make sure Jellyfin is closed first. You'll have to re-enter server info after that.

**Comment by Darkhost1999** [comment]
This deleting cache is why Android and Android TV worked where web UI and media player did not.
So figuring out where the cache was from the Jellyfin documents and clearing it was all that was necessary to restore the normal functionality of all the clients.
Would be nice to have a taskbar tray icon -> right click -> clear cache and it clears the server + client if installed.

**Comment by jameskimmel** [comment]
I have that problem since updating to Server 10.9.6 and client applesilicon 1.11.0

**Comment by lachlan-00** [comment]
I've been getting this problem as well after multiple server and client updates.

10.9.7 server debian
1.11.1 client using flatpak arm (rpi5)

I have done a grep for `ellyfin` on my the client os. Deleted everything and get a black screen each time I reinstall.

I can access everything else except the home page.

Doesn't happen on Windows or debian amd64 using the deb.

**Comment by epixtm** [comment]
I have the same issue, tried both the Linux and Windows versions of the 1.11.1 client on Jellyfin 10.9.8. Even with reinstalling and clearing the cache/config in `~/.local`, `~/.cache`, and `%APPDATA%`, I still get a blank screen. Can confirm that jellyfin-web is also on 10.9.8 and it works fine too.

Downgrading `jellyfin-media-player` to **1.10.1** (bundling jellyfin-web 10.9.6) seems to be a viable workaround, though thumbnails are borked for me. Video playback is fine tho.
![image](https://github.com/user-attachments/assets/5c80930b-564a-4918-b3a5-4239a38b8617)

**Comment by jasLogic** [comment]
I had the same issue where every client (web, phone) was working except Jellyfin Media Player although the server was up to date.

I fixed it by updating my server *networking* config (nginx in my case) to the newest version given in the documentation.

I think the part that fixed it was removing the COOP/COEP headers which probably caused the issues.

**Comment by Makarov3821** [comment]
> I had the same issue where every client (web, phone) was working except Jellyfin Media Player although the server was up to date.
> 
> I fixed it by updating my server _networking_ config (nginx in my case) to the newest version given in the documentation.
> 
> I think the part that fixed it was removing the COOP/COEP headers which probably caused the issues.

Tried many types but only yours work, thanks a lot for your help!

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I don't know if my issue is the same because I don't even have a Jellyfin logo:

<img width="1304" height="778" alt="Image" src="https://github.com/user-attachments/assets/f48af72a-7ec8-4657-9c2b-58b95c6c4350" />

I am on flatpak fedora. I have checked my reverse proxy logs, it is not blocking anything. It works perfectly on Windows but can't get it to work here on flatpak. Could someone help ? Thanks in advance
